### PR TITLE
Certificate of Completion

### PR DESCRIPTION
**Pull request by rgaiacs**
@gvwilson and @katyhuff Just a proof of completion.

### CODE REVIEW

**Comment by katyhuff** [comment]
Just a grammar comment. That sentence in the image should probably not have so many "ands" in it. Unless you're teaching "task automation with R"... the following would be a better way to say it...

"... task automation with the UNIX shell, programming with R, and version control with Git."

**Comment by gvwilson** [comment]
I also think it would look better if the two sentences were combined into one paragraph - the line break after "run by Software Carpentry" looks odd to me.

**Comment by r-gaia-cs** [comment]
Updated.

The logo position is OK? I change it a little so instructors name don't cover it.

ana

I also want to make it customizable, see 9657682. The challenge is handle the box width. And Inkscape doesn't have lists.

bob

**Comment by gvwilson** [comment]
Almost perfect - there should be a comma after "R" (as in, "programming 
with R, and...") - if you take out the word "computational" and wrap, 
then "Python" should fit OK.

On 2015-06-11 8:59 PM, Raniere Silva wrote:
>
> Updated.
>
> The logo position is OK? I change it a little so instructors name 
> don't cover it.
>
> ana 
> <https://cloud.githubusercontent.com/assets/1506457/8121615/75cd55a0-1084-11e5-8965-461409ea68b3.jpg>
>
> I also want to make it customizable, see 9657682 
> <https://github.com/swcarpentry/certification/commit/96576826fed3dad8cfa3f51a59e19f3c0436a0b6>. 
> The challenge is handle the box width. And Inkscape doesn't have lists.
>
> bob 
> <https://cloud.githubusercontent.com/assets/1506457/8121618/803254c8-1084-11e5-971e-270d835b7976.jpg>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/certification/pull/3#issuecomment-111318025>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by r-gaia-cs** [comment]
Small reword of the text and "automatically" wrap of the text:

ana

Added option for version control system:

bob

I didn't included SQL because we don't require workshops to taught it.

I also squashed the commits.

**Comment by gvwilson** [comment]
+1 from me - only change (small) would be "a, b, and c" for instructors' 
names when there are three or more.

**Comment by katyhuff** [comment]
Seems good!

**Comment by rgaiacs** [comment]
I think this was merged by @gvwilson. Closing for now.

**Pull request closed without merging**
