### PR TITLE
Update logos on certificates

### PR DESCRIPTION
**Pull request by fmichonneau**
Updated Data Carpentry Instructor certificate using DC logo:

screenshot from 2018-02-13 17-10-01

Updated Instructor Trainer certificate using "The Carpentries" logo:
screenshot from 2018-02-13 17-11-01

### CODE REVIEW

**Comment by fmichonneau** [comment]
I don't have write access to this repo. Please comment/request changes, or merge.

**Comment by kariljordan** [comment]
I will see if I can give you access @fmichonneau, and will merge in the meantime.

**Comment by kariljordan** [comment]
@jduckles can help.

**Comment by jduckles** [comment]
You have merge permissions now. @fmichonneau can you change the language in the text on the Trainer cert to be "The Carpentries" instead of Software Carpentry?

**Comment by fmichonneau** [comment]
Thanks for catching this @jduckles, I updated the text.

**Pull request merged**
